-- CreateEnum
CREATE TYPE "PlanTier" AS ENUM ('FREE', 'STARTER', 'PROFESSIONAL', 'AGENCY', 'ENTERPRISE');

-- AlterTable
ALTER TABLE "User"
  ADD COLUMN "plan" "PlanTier" NOT NULL DEFAULT 'FREE',
  ADD COLUMN "aiCreditsUsed" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "aiCreditsResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
